### ISSUE TITLE
Static themes

### ISSUE THREAD

**Issue by 23jams** [OlivierTD/team-rocket#11]
As a user, I would like to customize the look of the app to suit my preferences by being able to select 2 more color themes.

Currently there are only 2 themes, adding two more would boost user experience.

[SP: 3]
[Value: high]
[Risk: low]

**Tasks breakdown:**

- [x] Find the relevant area in the code to be modified (1hr)

- [x] Pick 2 colors to add as an option (0.5hr)

- [x] Implement the story (6 hrs)

**Implementation breakdown:**

1-Add 2 more color option buttons in theme settings #48
2-Make the 2 new theme color buttons functional #49 

**Testing**

Unit tests: 
Still working out a better way to test this functionality itself. #80 
Currently the test checks to see if these values have been initialized or not, if they are not initialized the system would not be able to change themes.  

https://github.com/OlivierTD/team-rocket/blob/56a4887e05c210d6e1a84cb509bb7dcf7fe06fb2/app/src/test/java/StaticThemeTest/testStaticTheme.java#L1-L45

Instrumented tests:

https://github.com/OlivierTD/team-rocket/blob/a0ad8fc343269d9eb9df73ade6f0ddc24755648c/app/src/androidTest/java/de/test/antennapod/ui/PreferencesTest.java#L65-L115

**Demonstration Steps:**
1-Go to Navigation Bar
2-Click on Settings
3-Click on Select Theme
4-Select any Theme
