### ISSUE TITLE
Random Episode feature (previously Shuffle feature)

### ISSUE THREAD

**Issue by 23jams** [OlivierTD/team-rocket#12]
As a user who is indecisive, I would like the app to have a random episode button. When pressed, this button would choose an episode of a given podcast at random, and begin playing.

[SP: 3]
[Value: low]
[Risk: low]

**Task breakdown:**

- [x] Plan out how episode playback works (1h)
- [x] Define the implementation breakdown (1h)
- [x] Divide tasks to assignee (0.5h)
- [x] Implement the story (6h)

**Implementation Breakdown:**

1 - Before choosing an episode to play, there should be a "Random Episode" button presented to the user. #56 
2 - By pressing the "Random Episode" button, playback begins with a randomly selected episode. #57 

**Testing:**

Unit test #77:

https://github.com/OlivierTD/team-rocket/blob/f31730d8aeb12b903806409db602ad7bee89986d/app/src/test/java/randomEpisodeTest/RandomEpisodeTest.java#L19-L30

Instrumented test #77:

https://github.com/OlivierTD/team-rocket/blob/f31730d8aeb12b903806409db602ad7bee89986d/app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java#L299-L319

**Demonstration Steps:**

1 - Navigate to a podcast page.
2 - If not subscribed but wish to do so, click Subscribe.
3 - Click on Open Podcast button.
4 - Click on Random Episode button. The app will now play a randomly chosen episode from the list of episodes.
