### ISSUE TITLE
Rearranging HomePage

### ISSUE THREAD

**Issue by SaiShan** [OlivierTD/team-rocket#143]
*"As a user, I want to view the multiple features on the Home Page in different tabs. "*
[SP: 2 ] 
[Value: high ]
[Risk: low ]

**Tasks breakdown:**

- [x]  Define the implementation breakdown [0.5 hours]

- [x] Implement the feature [12 hours]

**Implementation Breakdown:**

- [x] Create category fragment #154 

- [x] Create the different tabs on the home page #155 

- [x] Implement instrumented tests #156 

**Testing:**

Unit test:

After review, it was determined that no unit tests were required for this user story as there are no function that requires such testing. 

Instrumented test:

https://github.com/OlivierTD/team-rocket/blob/9e402783c7b9f49cbd09ec86aa52ecf7ecd66c8b/app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java#L436-L477

Acceptance test: 

![capture](https://user-images.githubusercontent.com/25252963/38955035-663e5ee0-4321-11e8-864d-79173c1203be.PNG)

**Demonstration Steps:**

1 - Navigate to home page.
2- Tabs are visible.
3 - Swipe to "FEATURED" tab.
4 - Scroll through toplist and suggested podcasts (if any)
5- Swipe to "CATEGORY" tab
6 - Scroll through categories.
7- Select desired category.
8 - Select desired podcast.
9 - Open the podcast.
10 - Select an episode to listen to.
11 - Stream to listen to episode or download to keep a local copy.

**Comment by guipadua** [comment]
Demoed. Tabs are there. Still to be done move the random button and search results will be moved to a new page.
UI tests so far are done, unit still to be done.

**Comment by SaiShan** [comment]
@guipadua This User Story is now fully implemented. It is eligible for TA signoff.
