### ISSUE TITLE
Setup working environment

### ISSUE THREAD

**Issue by OlivierTD** [OlivierTD/team-rocket#2]
As a student, I want to have a working environment so that I will be ready to implement new features.
[SP: 1] 
[Value: High]
[Risk: Low]

**Tasks breakdown:**
- [x] Install Android studio (0.5h)
- [x] Import project into Android studio (0.5h)
- [x] Let the app run (0.5h)
