### ISSUE TITLE
Manage "Outer" Workings of Multiple Queues

### ISSUE THREAD

**Issue by OlivierTD** [OlivierTD/team-rocket#38]
As a user, I want to be able to manage the "outer" part of my queues. This includes creating, deleting, viewing and accessing queue objects. The "inner" part of the multiple queue system is part of the user story #39 
[SP: 15]  
[Value: High]
[Risk: Low]

**Tasks breakdown:**
- [x] Plan out how queues will work (1h)
- [x] Define the implementation breakdown (1h)
- [x] Divide tasks to assignee (0.5h)
- [x] Implement the story (10h)

**Implementation Breakdown:**

1 - Upon selecting Queue in the menu, display an activity where the user can add/delete/access queues. #14 [SP: 4]
2 - Adding queue #15 [SP: 3] 
3 - Display queue #44 [SP: 3] 
4 - Deleting queue #16 [SP: 3]
5 - Accessing a queue #17  [SP: 2]

**Testing:**

Unit tests:
https://github.com/OlivierTD/team-rocket/blob/6e2e12774099bf691e76201da563052345cc9be8/app/src/test/java/mutipleQueueTests/QueueListFragmentTest.java#L1-L62

Instrumented tests:
https://github.com/OlivierTD/team-rocket/blob/0963021d46ee13a6deba67abbb1e47cd25bceae6/app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java#L299-L322

**Demonstration Steps:**
1 - Navigate to queues page.
2 - Click on Create New Queue button (2x)
3 - Click on Delete button next to a Queue
4 - Click on Queue to access it
