### ISSUE TITLE
Manage "Inner" Workings of Multiple Queues

### ISSUE THREAD

**Issue by OlivierTD** [OlivierTD/team-rocket#39]
As a user, I want to be able to use the "inner" workings of the multiple queues system. Once a user access a queue in #38, they will be able to see appropriate information of that queue once this user story is completed.
[SP: 15] 
[Value: High]
[Risk: High]

**Tasks breakdown:**
- [x] Define the implementation breakdown (1h)
- [x] Divide tasks to assignees (0.5h)
- [x] Implement the story (8h)

**Implementation Breakdown:**

1 - Adding episode to a specific queue (give the user the choice to decide which queue) #18
2 - Remove episode #40
3 - Remove or Modify the automatic queuing system (when you download a new podcast) #19
4 - Display episodes in queue fragment #116 
5 - Implement RxJava for episodes #117 

**Testing:**

1 - Unit tests added: #171 
https://github.com/OlivierTD/team-rocket/blob/5e4196c1fe51f442045745db4d4a26c675652e8f/app/src/test/java/multipleQueueTests/QueueFragmentTest.java#L1-L69

2 - UI test added: #175 
https://github.com/OlivierTD/team-rocket/blob/5e4196c1fe51f442045745db4d4a26c675652e8f/app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java#L346-L396

3 - Acceptance test

![image](https://user-images.githubusercontent.com/17104689/38942688-712bdb44-42fd-11e8-92bd-25a70ca9d8c5.png)

**Demonstration Steps:**
1. Open Nav bar and access the queues page
2. Create a new queue and name it
3. Go to subscription page and search and subscribe to a podcast
4. Go to episodes page and add an episode to queue
5. Return to queues page and access the queue
6. Play the episode, pause the episode
7. Longclick the episode to open contextmenu, and remove the episode from the queue

**Comment by guipadua** [comment]
Demoed and it looks good. Add and remove multiple queue. Multiple Episodes on each queue, even of the same (that's the desired behaviour.) 
Check for tests, currently has some the other part of the story, but needs more.
