### ISSUE TITLE
Custom Colored Themes

### ISSUE THREAD

**Issue by anania-y** [OlivierTD/team-rocket#50]
As a user, I want to be able to pick a few colors to be part of a color theme that stays.

[SP: 6]  
[Value: High]
[Risk: Low]

**Tasks breakdown:**

- [x] Plan what the new activity page will contain (1h)
- [x] Create new activity with content (8h)
- [x] Make the content responsive (8h)

**Implementation Breakdown:**

- [x] New Activity Page for Custom Themes #89 [SP:2]
- [x] Functionality of Custom Themes Page #90 [SP:3]

Instrumented test:

https://github.com/OlivierTD/team-rocket/blob/ea36227209aba277fa3740a8c48a45327200c9eb/app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java#L434-L462

**Demonstration Steps:**

1-Go to Navigation Bar
2-Click on Custom Theme 
3-Click on Color 1
4-Select a color and press ok
5-Repeat steps 4 and 5 for buttons Color 2 and Color 3
6-Click Set

**Comment by guipadua** [comment]
Demoed the selection and change. Missing the top bar and the persistence on the database.

**Comment by anania-y** [comment]
@guipadua  The fixes you mentioned have been applied!
