### ISSUE TITLE
Search by categories

### ISSUE THREAD

**Issue by SaiShan** [OlivierTD/team-rocket#54]
"As a user, I want to be able to search podcasts by categories."

[SP: 5 points ] 
[Value: High]
[Risk: Low]

**Tasks breakdown:**

- [x] Define the implementation breakdown [0.5 hours]

- [x] implement the feature [7 hours]

**Implementation Breakdown:**

- [x] Create the layout to perform a search by categories. #107 

- [x] Implement the search by categories functionality. #108 

- [x] Search by Categories: Instrumented tests. #110 

**Testing:**

Instrumented test:

https://github.com/OlivierTD/team-rocket/blob/f21e32c517a088b7624c2dda52ce71883d109f7b/app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java#L365-L401

Unit test:

After review, attempted tests were not useful. Also, the same issue as for the centralized search was encountered in regards to dependencies. 

Acceptance test: 

![capture](https://user-images.githubusercontent.com/25252963/38954007-7fd3118c-431e-11e8-858f-903b1eec23f5.PNG)

**Demonstration Steps:**

1- Navigate to Search Podcast page
2- Select the "CATEGORY" button.
3- Select the desired category to perform the search.
4- Search result list is displayed to the end user.
