### ISSUE TITLE
Multiple Queue

### ISSUE THREAD

**Issue by 23jams** [OlivierTD/team-rocket#6]
As a user, I want to create more than one queue so that I can change to a different podcast without disrupting the order of the first queue.

[SP: 30]
[Value: High]
[Risk: High]

**Task breakdown:**
- [x] Find and understand preexisting code that will be needed. (1h)
- [x] Plan out how the multiple queue system should behave. (1h)
- [x] Define the implementation breakdown (1h)
- [x] Divide tasks to assignees (0.5h)
- [ ] Implement the story (8h)
