### ISSUE TITLE
Centralized search

### ISSUE THREAD

**Issue by 23jams** [OlivierTD/team-rocket#7]
### User Story

As a user I want to be able to search for podcast from different libraries from the homescreen, without needing to go through many menus.

[SP: 6]
[Value: High]
[Risk: Low]

### Implementation Breakdown:

- [x] Create search bar for centralized search on home page #41
- [x] Search iTunes podcasts via centralized search #42
- [x] Search FYYD podcasts via centralized search #43
- [x] Merge results and remove duplicates #66 
- [x] Create unit and UI test #72 

#### Unit Test
Issues when attempting to mock dependencies (namely with FYYD) needed to perform a search for testing purposes.

#### UI Test
Issues with attempting to access the search bar as it is created dynamically in the central search fragment. This was done so that the search bar is not persisted throughout the view of the app seeing as the search bar is integrated into the menu bar.

### Demonstration Steps:
1 - Navigate to home page.
2- Select the search icon located at the top right.
3- Enter a search term
4- Search result list is displayed to user
