### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by 23jams** [OlivierTD/team-rocket#8]
As a user, I want the user interface to be simpler to use. 

[SP: 3] 
[Value: High]
[Risk:  Low]

**Tasks breakdown:**
- [x] Change the queues page by adding a "+" button to add a new queue
- [x] Change the queues page by adding a "trash" button to delete queues
- [x] Remove the "Search from iTunes" and "Search from FYYD" from the Add Podcast page (Since they are not necessary for we have a centralized search in the home page)
- [x] Fix the redirect to home (it still redirected to queues)
