### ISSUE TITLE
Suggested Podcast

### ISSUE THREAD

**Issue by 23jams** [OlivierTD/team-rocket#9]
As a user, I would like the app to recommend podcasts based on my current subscription preferences.

[SP: 7]
[Value: High]
[Risk: Low]

**Tasks breakdown:**

- [x] Define implementation breakdown (0.5hr)

- [x] Divide task to assignee (0.25hr)

- [x] Implement the story (6hrs)

**Implementation breakdown:**

1- Search top 5 most relevant Itunes podcasts #45 
2- Search top 5 most relevant FYYD podcasts #46 
3- Display top 10 suggested podcasts #47 
4- Display random subbed podcast's category #145
5- Creating UI and Unit tests #88 

#### Testing 
Unit test:

Unable to implement appropriate unit test due to needing too many dependencies to mock and account for. Furthermore, most required dependencies are final classes, further complicating the tests. This includes having to mock okhttp3 required for iTunes searches and fyydlin REST required for FYYD searches.

Instrumented test:

https://github.com/OlivierTD/team-rocket/blob/433d6d0e66d2f4273cb9a986edfa9e8b91930dac/app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java#L481-L507

#### Demonstration Steps

1. Subscribe to a podcast
2. Navigate to the home page
3. Suggested podcasts will be displayed

**Comment by davidlegare** [comment]
Instead of the original idea of keeping the subscribed podcasts' categories in memory, suggested podcasts now displays results based on a random subscibed podcast's category. 
This will allow for different suggested podcasts to be displayed every time the home page is loaded (assuming there are multiple categories the user is subscribed to).

**Comment by guipadua** [comment]
Looks good. Maybe add a way to refresh the suggested as soon as you add from the top list.
UI test done, unit tests not yet.
