### ISSUE TITLE
Random new podcast

### ISSUE THREAD

**Issue by davidlegare** [OlivierTD/team-rocket#91]
### User Story:
As a user, I would like to be able to view a random podcast with the option of viewing its category first to accept or decline said category podcast.

[SP: 5] 
[Value: medium]
[Risk: low]

#### Implementation Breakdown:

- [x] Add all podcast categories to storage #127
- [x] Get random podcast #128
- [x] Display random podcast to user #129
- [x] Display category to accept or decline #132

#### Unit Test
https://github.com/OlivierTD/team-rocket/blob/f9d87b15f9a3ccc78693b11910a0422b6927118b/app/src/test/java/randomPodcastTest/RandomPodcastFragmentTest.java#L23-L81

#### Implemented Test
https://github.com/OlivierTD/team-rocket/blob/f9d87b15f9a3ccc78693b11910a0422b6927118b/app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java#L345-L359

#### Acceptance Test
![image](https://user-images.githubusercontent.com/25251994/38965245-912fa136-4349-11e8-91df-5b641c08813d.png)

#### Demonstration Steps:

- Navigate to the home page
- Click on random podcast button
- Accept or decline the podcast category
