### ISSUE TITLE
Statistics Page

### ISSUE THREAD

**Issue by vartanbeno** [OlivierTD/team-rocket#92]
As a user, I would like there to be a page displaying statistics representing my usage of AntennaPod. The stats displayed as of 12:50 EST 03/30/2018 are:

- Number of subscriptions.
- Number of total hours spent listening to podcasts.
- Number of total hours spent listening to individual podcasts.

[SP: 4] 
[Value: high]
[Risk: low]

**Tasks breakdown:**

- [x] Plan out how adding a new fragment to the NavList works (1h)
- [x] Define the implementation breakdown (1h)
- [x] Divide tasks to assignee (0.5h)
- [x] Implement the story (6h)

**Implementation Breakdown:**

1 - Create a new Statistics fragment and add it to the NavList. #121 
2 - Create a new Statistics layout which will display the statistics. #123 
3 - Populate the fragment with useful and interesting statistics. #122 

**Testing:**

Instrumented test:
https://github.com/OlivierTD/team-rocket/blob/5b61be96a385ab1a568648c60d2e89807d1684de/app/src/androidTest/java/de/test/antennapod/ui/MainActivityTest.java#L415-L432

**Demonstration Steps:**

1 - Press on the hamburger button on the top right to open up the nav drawer.
2 - Press on the Statistics button to open up the fragment.
